language: python
dist: focal

python:
  - "3.12"
install:
  - pip install -r requirements.txt
script: echo "Testing"

deploy:
  provider: elasticbeanstalk
  access_key_id:
    secure: "Px1GRTe30aRga6ivMO3R94+z8v4goPfttZFFD0kt5LajVR7EfeyJdrlK8b2nrbUHxVpA3izCO2mfq2AznUSrZgphxXT9w6gakWtdG6PvZz8RZfBoAOLersAp91t5eFmXHqJnL1O6mAxBSUFWa9m0ZWDTRqHT9QgR5vqKfjEYy88iZLdt/bdaBCglpssj0Y+bsialBgIaWlfsBI5pyUYQHehzMracwlV0Fpk32vxauFajF/i8OmU6LINUPBe+UyCKzkrnT+gFyCYdwosqasMQ8wPlC+gfBB1yqc64N2Xy5O+jY+y33Alx3fjOvga1bTRsh7T+sRl1k8sIgTt2Juv//P3ssBuFogofnGlGzNEmEiBCrkJFPS+aDw1PqfEEEXeQaafVae7OhINQPMt1/zlULq2/dCcjAQ1cEj8wKn2JZGfBb0WZsyyEvS49ly318ybhCkwqxXPJpHs6HBBa5GBO2mXY58DkorTp6NFsyUEUvB79m5D8nsYm2EcgGQ77RB1X7+lhtgQVRkEh2tkBr3RcFSRbyehZf9yg5r9rGCuX+qm1nh5pYBUHlMDKpe2esxVUpDBTaqBD1buk+lCjXdMf8Y+IIx9bMeAodtlJ5yT7LAl63GTazDmlA862U+j9IlMFmOfA8uvrdy9dupA7jXJwCZCE4JVD+XX7MAthox9Ha30="
  secret_access_key:
    secure: "Af68Z8PE3PghoNb+3u79q8MPqM/3K1SsmpXoFPTpD4dTfrOKAOQGhctsGKFmEjwQuL83PLzyyLvAwKRrqeFRYwPNwZwKe0PvvkKriTr9obSILYiNuerbfd+8e5/rwlrBrXvhKVO4yixk61ez6Tqj2UWVzHe497yUEpmnRMLd3xrq8dMm5xH2lqUYF7xY2UnYK5NZmaoKGL+4ALVp1CFJcdx68EK4P8+IzbZAuRVpbD4Oljr/1zvhYbPj2t30glxZnwZevLu1V4951v8XGIUNbYBMs/uWZECvFw2uLzUpFD5aq/dpzkfjYe8RSQuZY4U4Y/1vtffMH6wIt5wb/+65Vu/WEUrPxo2MT6vYq0pnPcJqlSmo35DYX8sltrZ7zxyHVN4JQXYuc9ibPcMtE7TlVJTgYTFL4J6QXIKPddPuKaB96jA6w77nLht1sVwGY+kwV7x07TTt2NzpaB0gfvff3GgKTQ8TRwGmeWkb0inVMiL2/qPpZlIYmsvVio2LWE2wby96bxVouFEfgDfjx/GaL+yjFaIxSjaOxnkfMbMEHPje8IF2yHm1vTk9gxFg+zLQpz9M+sTUFMVhNxj6eHvWZN57MkHzk5L6bfw1tK04eGvMLANETGai6mlCzM4DnwGt/wH06PpE6fAEBUxRMTLkG/OIdOmotpFO07huq6RhP/E="
  region: "us-west-2"
  app: "polls-travis-app"
  env: "polls-travis-env"
  bucket_name: "elasticbeanstalk-us-west-2-940482403872"
  on:
    repo: IanC13/swe-app-travis
    branch: main
  skip_cleanup: 'true'