language: python
dist: focal
python:
- '3.12'
install:
- pip install -r requirements.txt
script:
  - echo "Running Script"
  - black . --check
  - flake8 .
  - coverage run manage.py test
  
after_success:
  - coverage report

deploy:
  provider: elasticbeanstalk
  access_key_id:
    secure: jrpMh2an1o5+9jiOpZhoeVx8G1SIUnwcokl/MluLz4GlBiIpz36un6xBf0PERV5KUSi79cwN1n+o9ESEevebUiYTGC/+498I0ZKnR8dPoebEFPR9nXxJZT1RGhwxZD15PbgnrH8lOB2GapFCN02+4d5vlXIQnlLcTa4PMrjU6zTCtnO41QHjWYllHdfi2r6t7oLn1R9lv/c+y6WbKzQ92k3XXwFt9ecr3f7Wcp6ko2d2UoejVgP3uladOFsvMkgqKEkW1IIXuYi1rgcXAnK37iIyVrLESGMuMatCgkD10Isy/BH44YHRqEFtFQuPikrZbe4nLxAW5dQQTbz0vPwY1IWY79bq6wxGvXDMokpB4YL+mqxS+QSZ4iK1qAbAqyP68r6XFAi/8xpMS1GsJuYfpkHemJORvenynePlxO2rm+PssvSiUv7tosazCQ3AWrKYhZERaEfk6aVG2xQTPqJw41Jnh0bU3X8PQK4Z+TXNndjuKH4ejXFtriFSEPz3vP/BO03j6/+kBTnGgVQ3BuBxJRgFpK+t3BQTM1PE4OOdFmy6oQIoQ4D9fMHWH7VLXN8na6+Zj73kolA6WTHLQJbTJ8/PqYH145yLVAxWASPZCUl1H0SjGWEVeP0tyEdW0WBNZdlMiVhZmR2ZfefejS/eqP9X8ChphnGemrn8QMIZ3Ls=
  secret_access_key:
    secure: wUjJFrQIye12wCagNV2KkvBsAwvpsklkP/SZtQW1Zaxte0B4hw/VGgXzAHkV0/crsR7C8pjblIjJ0xqiU9v9aPhsWq9mBl0xEGE58+3TDxRnjLgZZDzH0JJKJ5tExrpjIOdwQ4mtSNztzVMUOF6JI7AttMoO9v2A2wJEAo2P+dhssf5ijDG6LEhxgz9aIpgAIeZW1ZMKQ2ZqpWectFxMAhDNO92yCzTVtJhC2dxiHEg+NvMLAc30RoyS0rW/ATxrQvosi1aM5PL++uZsc/1bxADf3w332FOaSLn0gY7vKyAXWaOCAohH9YjM6kACD3JT5QzeiKlz7/SRyivCoxoBXyUfel7dnaRgDORnMrMsNZ5kBqWdy6WxT9u5NOPdtaPlC5oRE2KG+/pLH0UQIOXj5PnS/p6yCM/I6lgTe2yajpIgWddMjk68QidLXO3XqLbjWfJ30qWtULmiEpO6yLJzp+qBDaH/WCbDP0GgXLI+W9kXiYL8qKvqFpMeBmq6JVP8JqMlFYxC34m5nwjpln1Dk70VBhREWymMVkSCT2epNjxvfTNNyqcrDCcJvlNBOs1g8lSmA0cy27sM0qVM24TkVeRONjjckWpt0GxZVkj86l8XE8Ni3tJc3wnSJ75LbkubbK0YnMOeEt99HLJBaao7X5XQ6uEVdXEvhEK/625oQ58=
  region: us-west-2
  app: polls-travis-app
  env: polls-travis-env
  bucket_name: elasticbeanstalk-us-west-2-940482403872
  on:
    branch: main
    repo: IanC13/swe-app-travis
